import { Category, Listing, User, AdminAnalytics } from './types';

export const MOCK_USERS: Record<string, User> = {
  usr_1: {
    id: 'usr_1',
    name: 'Aria Vance',
    email: 'aria.vance@rivers.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    rating: 4.98,
    isVerified: true,
    trustScore: 99,
    salesCount: 142,
    location: 'Neo Tokyo / Shibuya District',
    joinedDate: 'March 2024',
  },
  usr_2: {
    id: 'usr_2',
    name: 'Marcus Sterling',
    email: 'marcus.s@rivers.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    rating: 4.92,
    isVerified: true,
    trustScore: 97,
    salesCount: 89,
    location: 'San Francisco, CA',
    joinedDate: 'January 2025',
  },
  usr_3: {
    id: 'usr_3',
    name: 'Elena Rostova',
    email: 'elena.r@rivers.io',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    isVerified: true,
    trustScore: 100,
    salesCount: 215,
    location: 'Zurich, Switzerland',
    joinedDate: 'November 2023',
  },
  usr_4: {
    id: 'usr_4',
    name: 'Kai Takahashi',
    email: 'kai.t@rivers.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    rating: 4.88,
    isVerified: true,
    trustScore: 94,
    salesCount: 64,
    location: 'Singapore, Marina Bay',
    joinedDate: 'February 2025',
  },
};

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat_cyberware',
    name: 'Cyberware & Wearables',
    slug: 'cyberware',
    icon: 'Cpu',
    description: 'Next-gen Neural Interfaces, Haptic Gear & AR Glasses',
    itemCount: 412,
  },
  {
    id: 'cat_vehicles',
    name: 'Hyper Electric Mobility',
    slug: 'vehicles',
    icon: 'Zap',
    description: 'Electric Hydrofoils, Autonomous Skaters & EV Supercars',
    itemCount: 198,
  },
  {
    id: 'cat_audio',
    name: 'Acoustics & Studio',
    slug: 'audio',
    icon: 'Headphones',
    description: 'Audiophile Planar Gear, Synthesizers & Spatial Audio',
    itemCount: 320,
  },
  {
    id: 'cat_displays',
    name: 'Displays & Compute',
    slug: 'displays',
    icon: 'Monitor',
    description: 'Curved OLED Rigs, Quantum Processing Workstations',
    itemCount: 540,
  },
  {
    id: 'cat_property',
    name: 'Luxury Havens & Lofts',
    slug: 'property',
    icon: 'Building',
    description: 'Minimalist Architectural Mansions & Panoramic Pods',
    itemCount: 88,
  },
  {
    id: 'cat_collectibles',
    name: 'Digital & Physical Fine Art',
    slug: 'collectibles',
    icon: 'Sparkles',
    description: 'Verified Chronographs, Rare Mechanical Workpieces',
    itemCount: 260,
  },
];

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 'lst_1',
    title: 'AeroGlide X9 Carbon Fiber Electric Hydrofoil Board',
    description: 'Pure adrenaline. High-modulus carbon fiber hull with custom dual-propulsion jet motor capable of 48 km/h over open water. Features Bluetooth telemetry remote control, 90-min fast-swappable battery stack, and Rivers Escrow verified inspection certificate.',
    price: 420000,
    currency: 'EGP',
    condition: 'LIKE_NEW',
    categoryId: 'cat_vehicles',
    categoryName: 'Hyper Electric Mobility',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Zurich, Switzerland',
    sellerId: 'usr_3',
    seller: MOCK_USERS.usr_3,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['Watercraft', 'Hydrofoil', 'Electric', 'CarbonFiber', 'RiversFlow'],
    viewCount: 1420,
    createdAt: '2026-10-04T12:00:00Z',
  },
  {
    id: 'lst_2',
    title: 'NeuralPulse VR-Pro Spatial Haptic Visor Edition',
    description: '8K per-eye micro-OLED resolution with sub-millimeter eye-tracking precision. Ships with full-body haptic feedback suit connector, active liquid cooling, and custom custom travel flight case.',
    price: 160000,
    currency: 'EGP',
    condition: 'NEW',
    categoryId: 'cat_cyberware',
    categoryName: 'Cyberware & Wearables',
    images: [
      'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Neo Tokyo / Shibuya',
    sellerId: 'usr_1',
    seller: MOCK_USERS.usr_1,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['VR', 'SpatialComputing', 'MicroOLED', 'Haptics', 'Neural'],
    viewCount: 2890,
    createdAt: '2026-10-05T09:30:00Z',
  },
  {
    id: 'lst_3',
    title: 'Minimalist Curved Ultrawide Workstation Monitor 49"',
    description: 'Dual QHD 240Hz OLED curve display with 0.03ms response time, Thunderbolt 4 100W PD hubs, ambient back-glow sync system, and zero dead pixel guarantee.',
    price: 92500,
    currency: 'EGP',
    condition: 'LIKE_NEW',
    categoryId: 'cat_displays',
    categoryName: 'Displays & Compute',
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'San Francisco, CA',
    sellerId: 'usr_2',
    seller: MOCK_USERS.usr_2,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['OLED', 'Ultrawide', 'Workstation', 'Setup', '49Inch'],
    viewCount: 940,
    createdAt: '2026-10-03T18:15:00Z',
  },
  {
    id: 'lst_4',
    title: 'Planar Magnetic Studio Headphones Signature Series',
    description: 'Open-back audiophile masterpiece with custom beryllium planar drivers, titanium headband structure, and balanced XLR cable assembly. Unmatched spatial soundstage clarity.',
    price: 120000,
    currency: 'EGP',
    condition: 'EXCELLENT',
    categoryId: 'cat_audio',
    categoryName: 'Acoustics & Studio',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Singapore, Marina Bay',
    sellerId: 'usr_4',
    seller: MOCK_USERS.usr_4,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['Audiophile', 'PlanarMagnetic', 'Studio', 'Acoustics', 'HiFi'],
    viewCount: 1120,
    createdAt: '2026-10-02T14:20:00Z',
  },
  {
    id: 'lst_5',
    title: 'Cyan-Flame Custom Anodized Mechanical Keypad',
    description: 'Machined 6063 aerospace aluminum case with custom hand-lubed magnetic hall-effect switches, RGB underglow diffuse ring, and PBT double-shot keycaps. Includes brass weight plate.',
    price: 32500,
    currency: 'EGP',
    condition: 'NEW',
    categoryId: 'cat_displays',
    categoryName: 'Displays & Compute',
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Neo Tokyo / Shibuya',
    sellerId: 'usr_1',
    seller: MOCK_USERS.usr_1,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['MechanicalKeyboard', 'Custom', 'HallEffect', 'RGB', 'Aluminum'],
    viewCount: 780,
    createdAt: '2026-10-05T16:00:00Z',
  },
  {
    id: 'lst_6',
    title: 'Titanium-Mesh Autonomous Drone Camera Rig',
    description: 'Obstacle avoidance AI suite with 360-degree LiDAR, Hasselblad 4/3 CMOS camera sensor, 45-minute battery endurance, and encrypted satellite stream relay.',
    price: 245000,
    currency: 'EGP',
    condition: 'LIKE_NEW',
    categoryId: 'cat_cyberware',
    categoryName: 'Cyberware & Wearables',
    images: [
      'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Zurich, Switzerland',
    sellerId: 'usr_3',
    seller: MOCK_USERS.usr_3,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['Drone', 'Aerial', 'Hasselblad', 'LiDAR', 'Cinematic'],
    viewCount: 3100,
    createdAt: '2026-10-01T11:45:00Z',
  },
];

export const INITIAL_ADMIN_ANALYTICS: AdminAnalytics = {
  activeListings: 1482,
  totalMarketplaceGmv: 214790000,
  escrowVolume: 57700000,
  userVerificationCount: 342,
  dailyTrafficCount: 48920,
  bnplFinancedVolume: 92250000,
  gmvGrowthPercent: 24.6,
  trafficSpikeData: [
    { time: '00:00', visitors: 12400, orders: 120 },
    { time: '04:00', visitors: 8900, orders: 85 },
    { time: '08:00', visitors: 24500, orders: 310 },
    { time: '12:00', visitors: 48900, orders: 620 },
    { time: '16:00', visitors: 56200, orders: 790 },
    { time: '20:00', visitors: 41800, orders: 540 },
  ],
  categoryBreakdown: [
    { category: 'Cyberware & Wearables', count: 412, value: 67500000 },
    { category: 'Hyper Electric Mobility', count: 198, value: 84000000 },
    { category: 'Displays & Compute', count: 540, value: 44500000 },
    { category: 'Acoustics & Studio', count: 320, value: 18790000 },
  ],
  recentVerifications: [
    {
      id: 'v_101',
      userId: 'usr_5',
      userName: 'Sora Tanaka',
      userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      documentType: 'PASSPORT',
      submittedAt: '12 mins ago',
      status: 'PENDING',
    },
    {
      id: 'v_102',
      userId: 'usr_6',
      userName: 'Dominic Cross',
      userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      documentType: 'BUSINESS_LICENSE',
      submittedAt: '28 mins ago',
      status: 'PENDING',
    },
    {
      id: 'v_103',
      userId: 'usr_7',
      userName: 'Amara Vance',
      userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
      documentType: 'ID_CARD',
      submittedAt: '1 hour ago',
      status: 'PENDING',
    },
  ],
};
