import { Category, Listing, User, AdminAnalytics } from './types';

export const MOCK_USERS: Record<string, User> = {
  usr_1: {
    id: 'usr_1',
    name: 'Tariq Al-Mansoor',
    email: 'tariq.m@opensooq.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    rating: 4.95,
    isVerified: true,
    trustScore: 99,
    salesCount: 142,
    location: 'Amman, Abdoun',
    joinedDate: 'March 2024',
    phone: '+962 7 9123 4567',
    whatsapp: '+962791234567',
  },
  usr_2: {
    id: 'usr_2',
    name: 'Kareem Hassan',
    email: 'kareem.h@opensooq.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    rating: 4.88,
    isVerified: true,
    trustScore: 97,
    salesCount: 89,
    location: 'Dubai, Marina',
    joinedDate: 'January 2025',
    phone: '+971 50 987 6543',
    whatsapp: '+971509876543',
  },
  usr_3: {
    id: 'usr_3',
    name: 'Layla Al-Zahra',
    email: 'layla.z@opensooq.io',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    rating: 5.0,
    isVerified: true,
    trustScore: 100,
    salesCount: 215,
    location: 'Riyadh, Al-Olaya',
    joinedDate: 'November 2023',
    phone: '+966 55 432 1098',
    whatsapp: '+966554321098',
  },
  usr_4: {
    id: 'usr_4',
    name: 'Omar Farooq',
    email: 'omar.f@opensooq.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    rating: 4.90,
    isVerified: true,
    trustScore: 95,
    salesCount: 64,
    location: 'Cairo, New Cairo',
    joinedDate: 'February 2025',
    phone: '+20 100 555 1234',
    whatsapp: '+201005551234',
  },
};

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat_cars',
    name: 'Cars & Vehicles',
    nameAr: 'سيارات ومركبات',
    slug: 'cars',
    icon: 'Car',
    description: 'Sedans, SUVs, Electric Vehicles, Motorcycles & Spare Parts',
    descriptionAr: 'سيارات، مركبات كهربائية، دراجات نارية وقطع غيار',
    itemCount: 1240,
    subcategories: [
      { id: 'sub_sedan', nameEn: 'Sedans', nameAr: 'سيارات صالون' },
      { id: 'sub_suv', nameEn: 'SUVs & 4x4', nameAr: 'سيارات دفع رباعي' },
      { id: 'sub_ev', nameEn: 'Electric Vehicles', nameAr: 'سيارات كهربائية' },
      { id: 'sub_parts', nameEn: 'Spare Parts & Accessories', nameAr: 'قطع غيار وإكسسوارات' },
    ],
  },
  {
    id: 'cat_realestate',
    name: 'Real Estate',
    nameAr: 'عقارات للإيجار والبيع',
    slug: 'realestate',
    icon: 'Building2',
    description: 'Apartments for Rent/Sale, Luxury Villas, Lands & Commercial',
    descriptionAr: 'شقق للإيجار والبيع، فلل فاخرة، أراضي ومحلات تجارية',
    itemCount: 890,
    subcategories: [
      { id: 'sub_rent', nameEn: 'Apartments for Rent', nameAr: 'شقق للإيجار' },
      { id: 'sub_sale', nameEn: 'Apartments for Sale', nameAr: 'شقق للبيع' },
      { id: 'sub_villas', nameEn: 'Villas & Houses', nameAr: 'فلل ومنازل' },
      { id: 'sub_land', nameEn: 'Lands & Commercial', nameAr: 'أراضي وتجاري' },
    ],
  },
  {
    id: 'cat_mobiles',
    name: 'Mobiles & Electronics',
    nameAr: 'موبايل وإلكترونيات',
    slug: 'mobiles',
    icon: 'Smartphone',
    description: 'Smartphones, Laptops, Tablets, OLED TVs & Gaming Consoles',
    descriptionAr: 'هواتف ذكية، لابتوبات، أجهزة لوحية وشاشات',
    itemCount: 2150,
    subcategories: [
      { id: 'sub_phones', nameEn: 'Smartphones', nameAr: 'هواتف ذكية' },
      { id: 'sub_laptops', nameEn: 'Laptops & Computers', nameAr: 'أجهزة لابتوب وكومبيوتر' },
      { id: 'sub_gaming', nameEn: 'Gaming Consoles', nameAr: 'أجهزة ألعاب فيديو' },
    ],
  },
  {
    id: 'cat_home',
    name: 'Home & Furniture',
    nameAr: 'أثاث ومستلزمات منزلية',
    slug: 'home',
    icon: 'Sofa',
    description: 'Living Room Sets, Kitchen Appliances, Bedrooms & Decor',
    descriptionAr: 'طقم كنب، أجهزة مطبخ، غرف نوم وديكور',
    itemCount: 670,
    subcategories: [
      { id: 'sub_sofa', nameEn: 'Sofas & Living Room', nameAr: 'طقم كنب وجلوس' },
      { id: 'sub_appliances', nameEn: 'Home Appliances', nameAr: 'أجهزة منزلية' },
      { id: 'sub_bedroom', nameEn: 'Bedrooms', nameAr: 'غرف نوم' },
    ],
  },
  {
    id: 'cat_jobs',
    name: 'Jobs & Services',
    nameAr: 'وظائف وخدمات',
    slug: 'jobs',
    icon: 'Briefcase',
    description: 'Job Vacancies, CV Publishing, Professional Maintenance & Services',
    descriptionAr: 'فرص عمل، سير ذاتية، وخدمات صيانة احترافية',
    itemCount: 430,
    subcategories: [
      { id: 'sub_job_openings', nameEn: 'Job Vacancies', nameAr: 'وظائف شاغرة' },
      { id: 'sub_services', nameEn: 'Home & Tech Services', nameAr: 'خدمات منزلي وتقنية' },
    ],
  },
  {
    id: 'cat_fashion',
    name: 'Fashion & Beauty',
    nameAr: 'أزياء وجمال',
    slug: 'fashion',
    icon: 'Shirt',
    description: 'Men & Women Clothing, Luxury Watches, Perfumes & Jewelry',
    descriptionAr: 'ملابس رجالي ونسائي، ساعات فاخرة وعطور',
    itemCount: 510,
    subcategories: [
      { id: 'sub_watches', nameEn: 'Luxury Watches', nameAr: 'ساعات فاخرة' },
      { id: 'sub_clothes', nameEn: 'Clothing & Shoes', nameAr: 'ملابس وأحذية' },
    ],
  },
  {
    id: 'cat_cyberware',
    name: 'Cyberware & Tech',
    nameAr: 'أجهزة تقنية متقدمة',
    slug: 'cyberware',
    icon: 'Cpu',
    description: 'VR Visors, Hydrofoils, Drone Cameras & Next-gen Tech',
    descriptionAr: 'أجهزة واقع افتراضي، زوارق هيدروفيل، وطائرات درون',
    itemCount: 380,
  },
];

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 'lst_101',
    title: 'Toyota Camry 2024 Hybrid Full Option - Mint Condition',
    titleAr: 'تويوتا كامري 2024 هايبرد فل كامل بحالة الوكالة',
    description: 'Toyota Camry Hybrid model 2024, full option with panoramic sunroof, leather seats, 12.3" infotainment screen, radar cruise control, and 360-degree cameras. Original paint, zero accidents, agency warranty active.',
    price: 26500,
    currency: 'JOD',
    condition: 'LIKE_NEW',
    categoryId: 'cat_cars',
    categoryName: 'Cars & Vehicles',
    subCategory: 'sub_sedan',
    images: [
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Amman, Abdoun',
    city: 'Amman',
    district: 'Abdoun',
    country: 'JO',
    sellerId: 'usr_1',
    seller: MOCK_USERS.usr_1,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['Toyota', 'Camry', 'Hybrid', '2024', 'FullOption'],
    viewCount: 1840,
    createdAt: '2026-10-08T10:15:00Z',
    featured: true,
    specs: {
      Year: '2024',
      Mileage: '12,500 km',
      Transmission: 'Automatic',
      Fuel: 'Hybrid',
      Color: 'Pearl White',
    },
  },
  {
    id: 'lst_102',
    title: 'iPhone 16 Pro Max 512GB Desert Titanium - Sealed In Box',
    titleAr: 'آيفون 16 برو ماكس 512 جيجا تيتانيوم صحراوي كفالة رسمية',
    description: 'Brand new factory sealed Apple iPhone 16 Pro Max 512GB in Desert Titanium. Comes with 1-year official Apple local agency warranty, tax receipt included.',
    price: 1050,
    currency: 'JOD',
    condition: 'NEW',
    categoryId: 'cat_mobiles',
    categoryName: 'Mobiles & Electronics',
    subCategory: 'sub_phones',
    images: [
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Amman, Seventh Circle',
    city: 'Amman',
    district: '7th Circle',
    country: 'JO',
    sellerId: 'usr_1',
    seller: MOCK_USERS.usr_1,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['iPhone16ProMax', 'Apple', 'Sealed', 'DesertTitanium'],
    viewCount: 3200,
    createdAt: '2026-10-08T08:30:00Z',
    featured: true,
    specs: {
      Brand: 'Apple',
      Storage: '512GB',
      Color: 'Desert Titanium',
      Warranty: '1 Year Official',
    },
  },
  {
    id: 'lst_103',
    title: 'Luxury 3BR Apartment For Rent in Abdoun with Panoramic Terrace',
    titleAr: 'شقة فاخرة مفروشة 3 نوم للإيجار في عبدون مع تراس بانورامي',
    description: '220 sqm luxury modern apartment featuring 3 master bedrooms, spacious living hall, modern fitted Italian kitchen, central heating, inverter A/C units, underground parking, and private security.',
    price: 14000,
    currency: 'JOD',
    condition: 'LIKE_NEW',
    categoryId: 'cat_realestate',
    categoryName: 'Real Estate',
    subCategory: 'sub_rent',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Amman, Abdoun',
    city: 'Amman',
    district: 'Abdoun',
    country: 'JO',
    sellerId: 'usr_3',
    seller: MOCK_USERS.usr_3,
    safetyBadge: true,
    flowFinanceEligible: false,
    status: 'ACTIVE',
    tags: ['ApartmentForRent', 'Abdoun', 'Luxury', 'PanoramicTerrace'],
    viewCount: 1450,
    createdAt: '2026-10-07T14:20:00Z',
    featured: true,
    specs: {
      Area: '220 m²',
      Bedrooms: '3 Master',
      Bathrooms: '4',
      Floor: '3rd Floor',
      Furnished: 'Fully Furnished',
    },
  },
  {
    id: 'lst_104',
    title: 'Modern 7-Seater Italian Leather Living Room Sofa Set',
    titleAr: 'طقم كنب تركي فاخر 7 مقاعد بحالة الممتازة',
    description: 'High-end imported Italian leather sofa set. Includes 3-seater, 2-seater, and two single armchairs with matching coffee table. Clean, smoke-free home.',
    price: 850,
    currency: 'JOD',
    condition: 'EXCELLENT',
    categoryId: 'cat_home',
    categoryName: 'Home & Furniture',
    subCategory: 'sub_sofa',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Amman, Khalda',
    city: 'Amman',
    district: 'Khalda',
    country: 'JO',
    sellerId: 'usr_4',
    seller: MOCK_USERS.usr_4,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['SofaSet', 'LivingRoom', 'ItalianLeather', 'Furniture'],
    viewCount: 920,
    createdAt: '2026-10-06T18:40:00Z',
    specs: {
      Material: 'Italian Genuine Leather',
      Capacity: '7 Persons',
      Color: 'Beige / Warm Grey',
    },
  },
  {
    id: 'lst_105',
    title: 'AeroGlide X9 Carbon Fiber Electric Hydrofoil Board',
    titleAr: 'لوح هيدروفيل كربون كهربائي آيرو جلايد X9 متطور',
    description: 'Pure adrenaline. High-modulus carbon fiber hull with custom dual-propulsion jet motor capable of 48 km/h over open water. Features Bluetooth remote control and fast-swappable battery.',
    price: 4200,
    currency: 'JOD',
    condition: 'LIKE_NEW',
    categoryId: 'cat_cyberware',
    categoryName: 'Cyberware & Tech',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Aqaba, Tala Bay',
    city: 'Aqaba',
    district: 'Tala Bay',
    country: 'JO',
    sellerId: 'usr_2',
    seller: MOCK_USERS.usr_2,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['Watercraft', 'Hydrofoil', 'Electric', 'CarbonFiber'],
    viewCount: 1420,
    createdAt: '2026-10-05T12:00:00Z',
    specs: {
      Speed: '48 km/h',
      Battery: '90-min swappable',
      Material: 'High-Modulus Carbon',
    },
  },
  {
    id: 'lst_106',
    title: 'MacBook Pro 16" M3 Max 36GB RAM 1TB SSD Space Black',
    titleAr: 'ماك بوك برو 16 إنش M3 Max رام 36 جيجا هارد 1 تيرا اسود فضائي',
    description: 'Apple MacBook Pro 16-inch M3 Max chip with 14-core CPU and 30-core GPU. Liquid Retina XDR display, battery health 99%, only 14 battery cycles. Includes original MagSafe charger and leather sleeve.',
    price: 2400,
    currency: 'JOD',
    condition: 'LIKE_NEW',
    categoryId: 'cat_mobiles',
    categoryName: 'Mobiles & Electronics',
    subCategory: 'sub_laptops',
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=1200&q=80',
    ],
    location: 'Amman, Jubeiha',
    city: 'Amman',
    district: 'Jubeiha',
    country: 'JO',
    sellerId: 'usr_1',
    seller: MOCK_USERS.usr_1,
    safetyBadge: true,
    flowFinanceEligible: true,
    status: 'ACTIVE',
    tags: ['MacBookPro', 'M3Max', 'Apple', 'SpaceBlack', 'Laptop'],
    viewCount: 2110,
    createdAt: '2026-10-06T11:15:00Z',
    specs: {
      Processor: 'Apple M3 Max',
      RAM: '36GB Unified',
      Storage: '1TB SSD',
      Screen: '16.2" Liquid Retina XDR',
    },
  },
];

export const INITIAL_ADMIN_ANALYTICS: AdminAnalytics = {
  activeListings: 1482,
  totalMarketplaceGmv: 214790000,
  escrowVolume: 57700000,
  userVerificationCount: 342,
  dailyTrafficCount: 48920,
  bnplFinancedVolume: 92250000,
  gmvGrowthPercent: 24.6,
  trafficSpikeData: [
    { time: '00:00', visitors: 12400, orders: 120 },
    { time: '04:00', visitors: 8900, orders: 85 },
    { time: '08:00', visitors: 24500, orders: 310 },
    { time: '12:00', visitors: 48900, orders: 620 },
    { time: '16:00', visitors: 56200, orders: 790 },
    { time: '20:00', visitors: 41800, orders: 540 },
  ],
  categoryBreakdown: [
    { category: 'Cars & Vehicles', count: 1240, value: 84000000 },
    { category: 'Real Estate', count: 890, value: 67500000 },
    { category: 'Mobiles & Electronics', count: 2150, value: 44500000 },
    { category: 'Home & Furniture', count: 670, value: 18790000 },
  ],
  recentVerifications: [
    {
      id: 'v_101',
      userId: 'usr_5',
      userName: 'Sora Tanaka',
      userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      documentType: 'PASSPORT',
      submittedAt: '12 mins ago',
      status: 'PENDING',
    },
    {
      id: 'v_102',
      userId: 'usr_6',
      userName: 'Dominic Cross',
      userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      documentType: 'BUSINESS_LICENSE',
      submittedAt: '28 mins ago',
      status: 'PENDING',
    },
  ],
};
